Rails/Projekte/rails_app/config/routes.rb
Rails.application.routes.draw do
  
  resources :categories
  root 'events#index'
  
  get 'signup' => 'users#new'

  resource :session
  resources :users
  resources :events do
  	resources :likes
	resources :registrations
  end
end

Rails/Projekte/rails_app/app/models/event.rb
class Event < ApplicationRecord
	has_many :registrations, :dependent => :destroy
	has_many :likes, dependent: :destroy
	has_many :likers, through: :likes, source: :user

	has_many :categorizations, dependent: :destroy
	has_many :categories, through: :categorizations

	validates :name, :description, :location, presence: true
	validates :description, length: { minimum: 25 }
	validates :price, numericality: { greater_than_or_equal_to: 0 }

	def free?
		price.blank? || price.zero?
	end
end

Rails/Projekte/rails_app/app/controllers/events_controller.rb
class EventsController < ApplicationController
	before_action :set_event, only: [:show, :edit, :update, :destroy]
	before_action :require_signin, :except => [:index]
	before_action :require_admin, :except => [:index, :show]
	
	def index
		@events = Event.all
	end

	def show
		@likers = @event.likers
		@categories = @event.categories
	end

	def new
		@event = Event.new
	end

	def create
		@event = Event.new(event_params)
		if @event.save
			redirect_to events_path
		else
			render :new
		end
	end

	def edit
	end

	def update
		@event.update(event_params)
		redirect_to events_path
	end

	def destroy
		@event.destroy
		redirect_to events_path
	end

	private


		def set_event
			@event = Event.find(params[:id])
		end

		def event_params
			params.require(:event).permit(:name, :description, :location, :price, :start_date, :category_ids => [])
		end
end

Rails/Projekte/rails_app/app/helpers/events_helper.rb
module EventsHelper

	def format_price(event)
		if event.free?
			#"<strong>Free</strong>".html_safe
			content_tag(:strong, 'FREE')
		else
			number_to_currency(event.price, unit: "€", separator: ",", delimiter: ".", format: "%n %u")
		end
	end
end

Rails/Projekte/rails_app/app/views/events/_form.html.erb
<%= form_for(@event) do |f| %>
	
	<% if @event.errors.any? %>
		<div class="panel">
			<h2>Der Datensatz <%= @event.class.name.titleize.downcase %> konnte nicht gespeichert werden</h2>
			<p>
			Korrigieren Sie bitte  <%= pluralize(@event.errors.count, 'den', plural: 'die' ) %> Fehler.</p>
			<p>
				<ul>
					<% @event.errors.full_messages.each do |message| %>
						<li><%= message %></li>
					<% end %>
				</ul>
			</p>
		</div>
	<% end %>
	<p>
		<%= f.label :name %>
		<%= f.text_field :name %>
	</p>
	<p>
		<%= f.label :description %>
		<%= f.text_area :description %>
	</p>
	<p>
		<%= f.label :location %>
		<%= f.text_field :location %>
	</p>
	<p>
		<%= f.label :price %>
		<%= f.number_field :price %>
	</p>
	<p>
		<%= f.label :start_date %>
		<%= f.datetime_select :start_date %>
	</p>

	<p>
		<%= f.label :category_ids %>
		<%= f.collection_check_boxes(:category_ids, Category.all, :id, :name) %>
	</p>
	<p><%= f.submit %></p>

<% end %>

Rails/Projekte/rails_app/app/views/events/edit.html.erb
<h1>Event editieren</h1>

<%= render "form" %>

Rails/Projekte/rails_app/app/views/events/index.html.erb
<h1><%= pluralize(@events.count, "Event", plural: "Events" ) %></h1>

<table>
	<tr>
		<th>Name</th>
		<th>Beschreibung</th>
		<th>Ort</th>
		<th>Preis</th>
		<th>Beginn</th>
		<th>Registrierungen</th>
		<th>Show</th>
		<th>Edit</th>
		<th>Del</th>
	</tr>
	<% @events.each do |event| %>
		<tr>
			<td><%= event.name %></td>
			<td><%= truncate(event.description, length: 30) %></td>
			<td><%= event.location %></td>
			<td><%= format_price(event) %></td>
			<td><%= event.start_date %></td>
			<% if current_user %>
				<td><%= link_to "Registrations", event_registrations_path(event.id) %></td>
				<td><%= link_to "Show", event_path(event.id) %></td>
				<% if current_user_admin? %>
					<td><%= link_to 'Edit', edit_event_path(event.id) %></td>
					<td><%= link_to 'Del', event_path(event.id), method: :delete, data: { confirm: 'Sicher löschen?'} %></td>
				<% end %>
			<% end %>
		</tr>
	<% end %>

</table>

<p><%= link_to "Neuen Event", new_event_path if current_user_admin? %></p>

Rails/Projekte/rails_app/app/views/events/new.html.erb
<h1>Neuer Event</h1>

<%= render "form" %>

Rails/Projekte/rails_app/app/views/events/show.html.erb
<h1><%= @event.name %></h1>

<p><%= @event.description %></p>

<h3>When</h3>
<p><%= @event.start_date %></p>

<h3>Where</h3>
<p><%= @event.location %></p>

<h3>Price</h3>
<p><%= format_price @event %></p>

<h3>Categories</h3>
<ul>
	<% @categories.each do |category| %>
		<li><%= category.name %></li>
	<% end %>
</ul>


<p>
	<% if like = Like.where(user_id: current_user.id, event_id: @event.id).first %>
		<%= link_to 'DISLIKE', event_like_path(@event.id, like.id), method: :delete, class: 'button alert' %>
	<% else %>	
		<%= button_to 'LIKE', event_likes_path(@event), class: 'button primary' %>
	<% end %>
</p>

<% if @likers.any? %>
	<h3>LIKERS</h3>
	<ul>
		<% @likers.each do |user| %>
			<li><%= user.email %></li>
		<% end %>
	</ul>
<% end %>


<p><%= link_to "Alle Events anzeigen", events_path %></p>