Rails/Projekte/lib/config/routes.rb
Rails.application.routes.draw do
  
	root 'authors#index'
	get 'signup' => 'users#new'
	resource :session
  resources :users do
  	resources :lendings
  end
	resources :authors do
	 	resources :books
	end
 end

Rails/Projekte/lib/app/views/layouts/_top_bar.html.erb
<div class="top-bar">
  <div class="top-bar-left">
    <ul class="dropdown menu" data-dropdown-menu>
      <li class="menu-text">Library</li>
      <% if current_user %>
        <li><%= link_to "Home", authors_path %></li>
        <li><%= link_to 'My lendings', user_lendings_path(current_user.id) %></li>

      <% end %>
    </ul>
  </div>
  <div class="top-bar-right">
    <ul class="menu">
      <% if current_user %>
        <%= current_user.login %>
        <%= link_to 'Logout', session_path, method: :delete %>
      <% else %>
        <li><%= link_to 'Sign UP', signup_path %></li>
        <li><%= link_to 'Sign IN', new_session_path %></li>
      <% end %>
    </ul>
  </div>
</div>

Rails/Projekte/lib/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />

    <title><%= content_for?(:title) ? yield(:title) : "Untitled" %></title>

    <%= stylesheet_link_tag    "application" %>
    <%= javascript_include_tag "application", 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
  </head>

  <body>
    <%= render 'layouts/top_bar' %>
    <%= yield %>

  </body>
</html>