Rails/Projekte/rails_app/config/routes.rb
Rails.application.routes.draw do
  
  resources :categories
  root 'events#index'
  
  get 'signup' => 'users#new'

  resource :session
  resources :users
  resources :events do
  	resources :likes
	resources :registrations
  end
end

Rails/Projekte/rails_app/app/views/layouts/_flash_messages.html.erb
<div class="panel">

	<% flash.each do |key, value| %>
		<%= content_tag(:p, value, :class => "flash_#{key}") %>
	<% end %>

</div>

Rails/Projekte/rails_app/app/views/layouts/_side_bar.html.erb
<h4>Sidebar</h4>

Rails/Projekte/rails_app/app/views/layouts/_top_bar.html.erb
<div class="top-bar">
  <div class="top-bar-left">
    <ul class="dropdown menu" data-dropdown-menu>
      <li class="menu-text">RAILS APP</li>
      <li><%= link_to 'Projekte', root_path %></li>
      <li><%= link_to 'Users', users_path if current_user %></li>
    </ul>
  </div>
  <div class="top-bar-right">
    <ul class="menu">
      <% if current_user %>
        <%= current_user.name %>
        <%= link_to 'Logout', session_path, method: :delete %>
      <% else %>
        <li><%= link_to 'Sign Up', signup_path %></li>
        <li><%= link_to 'Sign In', new_session_path %></li>
      <% end %>
    </ul>
  </div>
</div>

Rails/Projekte/rails_app/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />

    <title><%= content_for?(:title) ? yield(:title) : "Untitled" %></title>

    <%= stylesheet_link_tag    "application" %>
    <%= javascript_include_tag "application", 'data-turbolinks-track' => true %>
    <%= javascript_include_tag "vendor/modernizr" %>
    <%= csrf_meta_tags %>
  </head>

  <body>
    <div class="row">
      <div class="row float-right">
        <%= image_tag 'logo.png' %>  
      </div>
      <div class="clearfix"></div>
      
      <%= render 'layouts/top_bar' %>

      <div class="row">
        <%= render 'layouts/flash_messages' %>
        <div class="medium-3 columns">
          <%= render 'layouts/side_bar' %>
        </div>
        <div class="medium-9 columns" >
          <%= yield %>
        </div>
      </div>

    </div>
  </body>
</html>